// Joan Andrés (@Andres6936) Github.

#ifndef GOBLIN_TASKRESULT_HPP
#define GOBLIN_TASKRESULT_HPP

enum TaskResult
{
	TASKSUCCESS,
	TASKFAILNONFATAL,
	TASKFAILFATAL,
	TASKCONTINUE,
	TASKOWNDONE,
	PATHEMPTY
};

#endif //GOBLIN_TASKRESULT_HPP
